services:
  - type: web
    name: studyhub-web
    env: python
    plan: free
    buildCommand: ""
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers $WEB_CONCURRENCY

  - type: worker
    name: studyhub-worker
    env: python
    plan: free
    buildCommand: ""
    startCommand: sh start.sh
